repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
        -   id: check-yaml
        -   id: check-added-large-files
            args: ['--maxkb=10000']
    -   repo: local
        hooks: 
        - id: system
          name: Black
          entry: poetry run black 
          types: [python]
          language: system

    -   repo: local
        hooks:
        - id: system
          name: MyPy
          entry: poetry run mypy
          types: [python]
          language: system
