repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
        -   id: check-yaml
        -   id: check-added-large-files
            args: ['--maxkb=10000']
    -   repo: local
        hooks:
        - id: black
          name: Black
          entry: uv run black
          types: [python]
          language: system

    -   repo: local
        hooks:
        - id: mypy
          name: MyPy
          entry: uv run mypy
          types: [python]
          language: system
