[tox]
env_list = py312, py313
isolated_build = true

[gh-actions]
python =
    3.12: py312
    3.13: py313

[testenv]
runner = uv-venv-lock-runner
with_dev = true
extras = docs
commands =
    uv run python --version
    isort mlgw_bns/ tests/
    black mlgw_bns/ tests/
    mypy mlgw_bns/
    pytest -v --cov=mlgw_bns --junit-xml tests/test_results.xml {posargs}

[testenv:py313]
commands_post =
    sphinx-build docs docs/html
